name: Go Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    environment: main
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21 # Update this to the version of Go you're using

      # Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Run tests recursively
      - name: Run tests
        env:
          GEMINI_EXCHANGE_API_KEY: ${{ secrets.GEMINI_EXCHANGE_API_KEY }}
          GEMINI_EXCHANGE_API_SECRET: ${{ secrets.GEMINI_EXCHANGE_API_SECRET }}
          GEMINI_EXCHANGE_API_ENVIRONMENT: production
          LOGLEVEL: DEBUG
        run: go test ./... -v
